# whatever
name: Deploy to Firebase Hosting on PR
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.14.0'

      - name: Install Firebase tools
        run: npm install -g firebase-tools@9

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@3.12.0

      - name: NPM Install
        run: npm ci

      - name: NPM Build
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BENDOYLEGRAY_2F80A }}'
          channel-id: deploy
          projectId: bendoylegray-2f80a
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
